print("What year is it?")
year = input()
print("  .  :  . ")   
print(" '.  :  .'  "  )
print(".  '.:.'  .  "   )
print(".  .':'.  .  "  )
print(" .'  :  '.   "  )
print("   ' :  '     ")
print("HAPPY NEW YEAR")
print("!!!",year,"!!!")