print("Enter your name")
name = input()
print("Enter your last name")
familyname = input()
print("Enter your phone number")
pn = input()
print("First Name:", name)
print("Last Name:", familyname)
print("phone number:", pn)
print("\n Your registered name is",name,familyname)
print("Your phone number is", pn)